In [4]:
import pandas as pd

df_xgboost_results = pd.read_csv("./data/xgboost_results.csv")

df_text_sentiment = pd.read_csv("./data/text_data_sentiment.csv")

df_2015 = pd.read_csv(f"./data/{2015}-hmm.csv")

In [82]:
df_text_sentiment

,bearish,neutral,bullish,gvkey,year,positive_ratio,negative_ratio,uncertainty_ratio,litigious_ratio,strong_modal_ratio,weak_modal_ratio,constraining_ratio
0,0.010647,0.932460,0.056893,6831.0,2005,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.010647,0.932460,0.056893,6831.0,2005,14.336475,36.107684,20.084262,9.181377,1.721508,8.607541,15.501571
2,0.010647,0.932460,0.056893,6831.0,2005,11.462977,32.845934,27.141595,8.351260,2.087815,15.136659,17.232788
3,0.010647,0.932460,0.056893,6831.0,2005,15.449145,88.430342,67.825214,33.483333,4.292735,44.644444,18.893162
4,0.010647,0.932460,0.056893,6831.0,2005,1.812200,27.970756,30.752342,9.638794,4.589902,8.261823,16.989947
...,...,...,...,...,...,...,...,...,...,...,...,...
14642883,0.216606,0.662318,0.121076,1585.0,2025,10.050104,50.244623,42.407599,22.404015,9.761749,23.364187,18.411582
14642884,0.071191,0.834922,0.093886,116025.0,2025,11.332243,18.494871,22.995838,19.712353,8.063476,5.375650,11.649026
14642885,0.254874,0.622000,0.123126,28378.0,2025,5.413848,48.828519,36.801785,24.770432,4.403632,23.040434,20.056482
14642886,0.363818,0.513946,0.122235,36152.0,2025,6.493233,48.803657,43.238529,16.844458,4.509540,24.271935,17.378557
14642887,0.514792,0.327656,0.157551,39863.0,2025,14.648315,63.586694,52.260002,27.924097,9.542574,37.145590,20.179062

In [72]:
df_2016 =  pd.read_csv(f"./data/{2016}-hmm.csv")

In [5]:
df_xgboost_results_2015 = df_xgboost_results[
    (df_xgboost_results["date"] >= "2015-01-01") &
    (df_xgboost_results["date"] <= "2015-12-31")
]

df_xgboost_results_2015["date"]
df_xgboost_2015_new = df_xgboost_results_2015.copy()

df_xgboost_2015_new["date"] = pd.to_datetime(df_xgboost_2015_new["date"])
df_xgboost_2015_new["date"] = df_xgboost_2015_new["date"].dt.strftime("%Y%m%d").astype(int)

In [6]:
df_xgboost_2015_new

,Unnamed: 0,gvkey,date,predicted_return,actual_return,model_used
0,0,1096.0,20150130,0.008775,-0.121979,2014
1,1,1186.0,20150130,-0.019760,0.350143,2014
2,2,1262.0,20150130,0.011259,-0.093005,2014
3,3,1828.0,20150130,0.005781,-0.059300,2014
4,4,2055.0,20150130,-0.007752,0.182980,2014
...,...,...,...,...,...,...
65848,65848,184514.0,20151231,0.002644,-0.116662,2014
65849,65849,184500.0,20151231,0.005039,-0.098047,2014
65850,65850,184994.0,20151231,0.007123,-0.264706,2014
65851,65851,184259.0,20151231,0.007332,-0.040909,2014
65852,65852,184996.0,20151231,0.007356,0.042343,2014

In [7]:
df_text_sentiment_2015 = df_text_sentiment[df_text_sentiment["year"] == 2015]
df_text_sentiment_2015

,bearish,neutral,bullish,gvkey,year,positive_ratio,negative_ratio,uncertainty_ratio,litigious_ratio,strong_modal_ratio,weak_modal_ratio,constraining_ratio
668006,0.104199,0.791077,0.104724,25849.0,2015,3.201734,11.451620,16.046326,10.086262,15.587859,5.960064,5.502510
668007,0.104199,0.791077,0.104724,25849.0,2015,3.207590,12.850480,15.157064,10.564015,14.697759,5.970965,5.512574
668008,0.104199,0.791077,0.104724,25849.0,2015,7.729289,14.991172,16.370303,2.728384,18.189226,5.456768,9.554776
668009,0.104199,0.791077,0.104724,25849.0,2015,3.869481,13.075754,15.994451,8.724246,15.994451,6.300844,4.363571
668010,0.104199,0.791077,0.104724,25849.0,2015,3.201734,11.451620,16.046326,10.086262,15.587859,5.960064,5.502510
...,...,...,...,...,...,...,...,...,...,...,...,...
735410,0.013025,0.415522,0.571454,26725.0,2015,4.023475,8.057418,14.658031,12.958549,4.248705,4.886010,6.798139
735411,0.126433,0.800481,0.073086,26545.0,2015,4.304087,40.039795,47.617534,17.992593,6.899131,32.737055,16.371221
735412,0.011426,0.047881,0.940692,26335.0,2015,13.442939,51.056937,50.461852,15.058774,6.980889,35.602532,17.854902
735413,0.069627,0.889295,0.041078,26347.0,2015,0.000000,-59.411765,59.088235,0.000000,0.000000,0.000000,0.000000
735414,0.087995,0.845320,0.066685,182497.0,2015,-1.844564,19.845463,41.515723,43.320755,5.415094,12.635220,16.245283

In [8]:
df_2015 = df_2015[df_2015["date"] >= 20150000]
df_2015

        Unnamed: 0     gvkey  hmm_state      date
92892        92892    2137.0          0  20150130
92893        92893    2703.0          0  20150130
92894        92894    4669.0          0  20150130
92895        92895    6771.0          2  20150130
92896        92896    6946.0          0  20150130
...            ...       ...        ...       ...
102031      102031  184323.0          0  20151231
102032      102032   29962.0          2  20151231
102033      102033  184442.0          2  20151231
102034      102034  185138.0          2  20151231
102035      102035  179583.0          2  20151231

[9144 rows x 4 columns]

In [53]:
df = pd.merge(df_xgboost_2015_new, df_text_sentiment_2015, on="gvkey", how="left")

df = pd.merge(df, df_2015, on=["gvkey", "date"], how="left")

df

,Unnamed: 0_x,gvkey,date,predicted_return,actual_return,model_used,bearish,neutral,bullish,year,positive_ratio,negative_ratio,uncertainty_ratio,litigious_ratio,strong_modal_ratio,weak_modal_ratio,constraining_ratio,Unnamed: 0_y,hmm_state
0,0,1096.0,20150130,0.008775,-0.121979,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1186.0,20150130,-0.019760,0.350143,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1262.0,20150130,0.011259,-0.093005,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1828.0,20150130,0.005781,-0.059300,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2055.0,20150130,-0.007752,0.182980,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
661267,65852,184996.0,20151231,0.007356,0.042343,2014,0.046747,0.930802,0.022451,2015.0,12.758059,56.573437,49.992997,33.130333,7.982914,37.61948,18.663835,NaN,NaN
661268,65852,184996.0,20151231,0.007356,0.042343,2014,0.676926,0.193681,0.129393,2015.0,0.000000,0.000000,118.176471,0.000000,0.000000,0.00000,0.000000,NaN,NaN
661269,65852,184996.0,20151231,0.007356,0.042343,2014,0.676926,0.193681,0.129393,2015.0,0.000000,0.000000,118.176471,0.000000,0.000000,0.00000,0.000000,NaN,NaN
661270,65852,184996.0,20151231,0.007356,0.042343,2014,0.676926,0.193681,0.129393,2015.0,0.000000,0.000000,118.176471,0.000000,0.000000,0.00000,0.000000,NaN,NaN
661271,65852,184996.0,20151231,0.007356,0.042343,2014,0.676926,0.193681,0.129393,2015.0,12.758059,56.573437,49.992997,33.130333,7.982914,37.61948,18.663835,NaN,NaN

In [56]:
import xgboost as xgb
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import train_test_split
from scipy.stats import uniform, randint


X = df.drop(['Unnamed: 0_x', 'actual_return', 'model_used', 'year', 'Unnamed: 0_y', 'gvkey', 'date'], axis=1)

y = df['actual_return']

# Define the XGBoost regressor model
xgbr = xgb.XGBRegressor(objective='reg:squarederror',
                        n_estimators=1500,
                        eval_metric='rmse',
                        early_stopping_rounds=50,
                        n_jobs=-1,
                        tree_method='gpu_hist' # This enables GPU acceleration
                        )

# Define the parameter space for RandomizedSearchCV
param_distributions = {
    'learning_rate': uniform(0.005, 0.3),
    'max_depth': randint(10, 15),
    'subsample': uniform(0.5, 0.4),
    'colsample_bytree': uniform(0.5, 0.4),
    'gamma': uniform(0, 0.5),
    'min_child_weight': randint(1, 10),
    }

# Set up RandomizedSearchCV
random_search = RandomizedSearchCV(
    xgbr,
    param_distributions=param_distributions,
    n_iter=25,
    cv=5,
    scoring='neg_mean_squared_error',
    random_state=42,
    n_jobs=-1,
    verbose=1
)

# Split the data into training and testing sets for this year
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Perform the randomized search
random_search.fit(X_train, y_train, eval_set=[(X_test, y_test)], verbose=False)

# Get the best model from the search
best_model = random_search.best_estimator_

Fitting 5 folds for each of 25 candidates, totalling 125 fits

c:\Users\shoai\anaconda3\envs\MLCOURSE\lib\site-packages\xgboost\core.py:158: UserWarning: [19:57:06] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-08cbc0333d8d4aae1-1\xgboost\xgboost-ci-windows\src\common\error_msg.cc:27: The tree method `gpu_hist` is deprecated since 2.0.0. To use GPU training, set the `device` parameter to CUDA instead.

    E.g. tree_method = "hist", device = "cuda"

  warnings.warn(smsg, UserWarning)

In [67]:
df_xgboost_results_2016 = df_xgboost_results[
    (df_xgboost_results["date"] >= "2016-01-01") &
    (df_xgboost_results["date"] <= "2016-12-31")
]

df_xgboost_results_2016["date"]
df_xgboost_2016_new = df_xgboost_results_2016.copy()

df_xgboost_2016_new["date"] = pd.to_datetime(df_xgboost_2016_new["date"])
df_xgboost_2016_new["date"] = df_xgboost_2016_new["date"].dt.strftime("%Y%m%d").astype(int)

In [69]:
df_xgboost_2016_new

,Unnamed: 0,gvkey,date,predicted_return,actual_return,model_used
65853,65853,1096.0,20160129,0.092091,-0.025970,2015
65854,65854,1186.0,20160129,0.093667,0.126779,2015
65855,65855,1262.0,20160129,0.092102,-0.068678,2015
65856,65856,1828.0,20160129,0.090591,0.073554,2015
65857,65857,2055.0,20160129,0.093437,0.342691,2015
...,...,...,...,...,...,...
129474,129474,179583.0,20161230,0.093717,-0.058411,2015
129475,129475,184514.0,20161230,0.092370,-0.006024,2015
129476,129476,184500.0,20161230,0.092334,0.072424,2015
129477,129477,184259.0,20161230,0.093474,-0.041667,2015
129478,129478,184996.0,20161230,0.093688,0.128247,2015

In [70]:
df_text_sentiment_2016 = df_text_sentiment[df_text_sentiment["year"] == 2016]
df_text_sentiment_2016

,bearish,neutral,bullish,gvkey,year,positive_ratio,negative_ratio,uncertainty_ratio,litigious_ratio,strong_modal_ratio,weak_modal_ratio,constraining_ratio
735415,0.521430,0.376171,0.102399,9916.0,2016,3.000136,15.591231,23.799428,5.197576,3.282680,8.206699,14.228758
735416,0.521430,0.376171,0.102399,9916.0,2016,9.049000,8.480146,23.196001,1.131512,3.960293,6.223317,7.924528
735417,0.521430,0.376171,0.102399,9916.0,2016,13.477557,10.221194,19.522906,1.394493,2.788987,6.507635,6.510875
735418,0.039931,0.033659,0.926410,9916.0,2016,3.000136,15.591231,23.799428,5.197576,3.282680,8.206699,14.228758
735419,0.039931,0.033659,0.926410,9916.0,2016,9.049000,8.480146,23.196001,1.131512,3.960293,6.223317,7.924528
...,...,...,...,...,...,...,...,...,...,...,...,...
800430,0.712923,0.194022,0.093055,26709.0,2016,13.389777,50.568816,50.366915,21.777601,5.057334,32.408220,19.821423
800431,0.165539,0.635672,0.198789,29018.0,2016,21.917858,56.294561,53.377751,29.338742,11.341074,40.542643,22.548423
800432,0.050545,0.808921,0.140535,29817.0,2016,-0.016396,14.214086,26.577045,8.609465,3.743246,7.112167,19.092044
800433,0.224445,0.684510,0.091045,20180.0,2016,8.895024,28.751193,25.335037,11.640423,2.054192,8.901500,10.277096
800434,0.168219,0.801587,0.030195,14501.0,2016,0.000000,0.000000,502.250000,0.000000,0.000000,0.000000,0.000000

In [73]:
df_2016 = df_2016[df_2016["date"] >= 20160000]
df_2016

        Unnamed: 0     gvkey  hmm_state      date
93956       102036    1186.0          0  20160129
93957       102037    1262.0          2  20160129
93958       102038    2137.0          0  20160129
93959       102039    2369.0          0  20160129
93960       102040    2703.0          0  20160129
...            ...       ...        ...       ...
102389      110469  179624.0          1  20161230
102390      110470  184323.0          0  20161230
102391      110471   29962.0          0  20161230
102392      110472   10567.0          2  20161230
102393      110473  179583.0          0  20161230

[8438 rows x 4 columns]

In [81]:
df = pd.merge(df_xgboost_2016_new, df_text_sentiment_2016, on="gvkey", how="left")
print(df)

df = pd.merge(df, df_2016, on=["gvkey", "date"], how="left")

        Unnamed: 0     gvkey      date  predicted_return  actual_return  \
0            65853    1096.0  20160129          0.092091      -0.025970
1            65854    1186.0  20160129          0.093667       0.126779
2            65855    1262.0  20160129          0.092102      -0.068678
3            65856    1828.0  20160129          0.090591       0.073554
4            65857    2055.0  20160129          0.093437       0.342691
...            ...       ...       ...               ...            ...
643746      129478  184996.0  20161230          0.093688       0.128247
643747      129478  184996.0  20161230          0.093688       0.128247
643748      129478  184996.0  20161230          0.093688       0.128247
643749      129478  184996.0  20161230          0.093688       0.128247
643750      129478  184996.0  20161230          0.093688       0.128247

        model_used   bearish   neutral   bullish    year  positive_ratio  \
0             2015       NaN       NaN       NaN     NaN             NaN
1             2015       NaN       NaN       NaN     NaN             NaN
2             2015       NaN       NaN       NaN     NaN             NaN
3             2015       NaN       NaN       NaN     NaN             NaN
4             2015       NaN       NaN       NaN     NaN             NaN
...            ...       ...       ...       ...     ...             ...
643746        2015  0.568449  0.274201  0.157350  2016.0        0.000000
643747        2015  0.047688  0.927797  0.024515  2016.0        0.000000
643748        2015  0.047688  0.927797  0.024515  2016.0       10.890766
643749        2015  0.047688  0.927797  0.024515  2016.0       13.980353
643750        2015  0.047688  0.927797  0.024515  2016.0        0.000000

        negative_ratio  uncertainty_ratio  litigious_ratio  \
0                  NaN                NaN              NaN
1                  NaN                NaN              NaN
2                  NaN                NaN              NaN
3                  NaN                NaN              NaN
4                  NaN                NaN              NaN
...                ...                ...              ...
643746        0.000000         118.176471         0.000000
643747        0.000000         118.176471         0.000000
643748       51.881000          30.335576        42.857590
643749       59.699266          53.959712        20.110669
643750        0.000000         118.176471         0.000000

        strong_modal_ratio  weak_modal_ratio  constraining_ratio
0                      NaN               NaN                 NaN
1                      NaN               NaN                 NaN
2                      NaN               NaN                 NaN
3                      NaN               NaN                 NaN
4                      NaN               NaN                 NaN
...                    ...               ...                 ...
643746            0.000000           0.00000            0.000000
643747            0.000000           0.00000            0.000000
643748           10.464839          22.79840           21.181508
643749            9.742726          40.21997           18.865145
643750            0.000000           0.00000            0.000000

[643751 rows x 17 columns]

In [90]:
gvkey_date = df[['gvkey', 'date']]
X = df.drop(['Unnamed: 0_x', 'actual_return', 'model_used', 'year', 'Unnamed: 0_y', 'gvkey', 'date'], axis=1)

y = df['actual_return']

predictions = best_model.predict(X)
test_mse = mean_squared_error(y, predictions)

results_df = pd.DataFrame({
    'gvkey': gvkey_date['gvkey'],
    'date': gvkey_date['date'],
    'actual_values': y,
    'predicted_values': predictions
})

results_df['date'] = pd.to_datetime(results_df['date'].astype(str), format='%Y%m%d')
results_df.sort_values(by='date', inplace=True)
results_df

           gvkey       date  actual_values  predicted_values
256      16058.0 2016-01-06      -0.080368          0.309999
1341    123098.0 2016-01-11      -0.020482          0.309999
1120    107403.0 2016-01-11       0.120144          0.309999
2024    181743.0 2016-01-15      -0.116425          0.309999
2094    183748.0 2016-01-15      -0.039583          0.309999
...          ...        ...            ...               ...
608237   27252.0 2016-12-30       0.060359         51.099819
608238   27252.0 2016-12-30       0.060359         64.082535
608239   27252.0 2016-12-30       0.060359         64.082535
608267  187368.0 2016-12-30       0.016349         36.321800
644052  184996.0 2016-12-30       0.128247         64.033943

[644053 rows x 4 columns]

In [125]:
import numpy as np
sum = 0
sum2 = 0
for month in range(4, 13):
    filtered = results_df[(results_df['date'].dt.year == 2016) & (results_df['date'].dt.month == month)]
    filtered.sort_values(by='predicted_values', inplace=True)
    top = filtered.head(100).copy()
    bottom = filtered.tail(100).copy()
    monthly_return = bottom['actual_values'].mean() - top['actual_values'].mean()
    print(monthly_return, 'month')
    sum += np.log(monthly_return + 1)
    sum2 += monthly_return 
    print(sum, sum2)
print(sum2)
np.exp(sum) - 1

C:\Users\shoai\AppData\Local\Temp\ipykernel_3504\3117918568.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered.sort_values(by='predicted_values', inplace=True)

0.07261986000000001 month
0.07010412315138001 0.07261986000000001
0.02151841000000005 month
0.09139428078042419 0.09413827000000005
-0.009802870000000009 month
0.08154304631704666 0.08433540000000005
-0.05430946999999996 month
0.02570314755980701 0.03002593000000009
0.037829429999999976 month
0.06283459317436463 0.06785536000000006
0.022617670000000006 month
0.085200276172507 0.09047303000000007
-0.07028488000000001 month
0.012323213830681398 0.020188150000000057
0.027101769999999928 month
0.03906423431742588 0.047289919999999985
0.005513740000000017 month
0.044562829297994 0.05280366
0.05280366

0.04557066711781088