In [1]:
import K_Means_Clustering as km
import os
import pandas as pd
import trade_pairs as tp
import numpy as np
import statsmodels.api as sm
import matplotlib.pyplot as plt

In [2]:
year = 2015
for i in range(11):
    km.get_cointegrated_stocks_by_year(year+i)

has NaN values: False
Optimum Clusters: 6
has NaN values: False
Optimum Clusters: 6
has NaN values: False
Optimum Clusters: 7
has NaN values: False
Optimum Clusters: 7
has NaN values: False
Optimum Clusters: 7
has NaN values: False
Optimum Clusters: 8
has NaN values: False
Optimum Clusters: 7
has NaN values: False
Optimum Clusters: 7
has NaN values: False
Optimum Clusters: 6
has NaN values: False
Optimum Clusters: 9
has NaN values: False
Optimum Clusters: 8

In [3]:
year = 2015
trades = []
cointegrated_pairs_path = f"data/cointegrated-pairs-{year}.csv"
# if not os.path.exists(cointegrated_pairs_path):
#     df_cointegrated_pairs = km.get_cointegrated_stocks_by_year(2026 + i)
# else:
#     df_cointegrated_pairs = pd.read_csv(cointegrated_pairs_path)

df_returns = km.get_stock_returns_upto_year(year + 1)

In [4]:
temp = df_returns[df_returns["date"] >= 20140000]
temp
print("Does '14322' exist?", 'crsp_23536' in df_returns['id'].values)

Does '14322' exist? True

In [11]:
df_returns.tail(100000)

            date          id  stock_ret  price_index
697385  20140630  crsp_88912  -0.024261        100.0
697386  20140630  crsp_88924   0.016787        100.0
697387  20140630  crsp_88926   0.119318        100.0
697388  20140630  crsp_88940   0.018406        100.0
697389  20140630  crsp_88944  -0.018493        100.0
...          ...         ...        ...          ...
797380  20151231  crsp_93428  -0.116662        100.0
797381  20151231  crsp_93429  -0.098047        100.0
797382  20151231  crsp_93433  -0.264706        100.0
797383  20151231  crsp_93434  -0.040909        100.0
797384  20151231  crsp_93436   0.042343        100.0

[100000 rows x 4 columns]

In [2]:
df_combined = pd.DataFrame()
year = 2015
df_returns = km.get_stock_returns_upto_year(2026)
for i in range(11):
    cointegrated_pairs_path = f"data/cointegrated-pairs-{year+i}.csv"
    if not os.path.exists(cointegrated_pairs_path):
        df_cointegrated_pairs = km.get_cointegrated_stocks_by_year(year)
    else:
        df_cointegrated_pairs = pd.read_csv(cointegrated_pairs_path)
    
    for j in range(len(df_cointegrated_pairs)):
        stock1_label = df_cointegrated_pairs.iloc[j, 0]
        stock2_label = df_cointegrated_pairs.iloc[j, 1]
        series1 = df_returns[df_returns["id"] == stock1_label].copy()
        series2 = df_returns[df_returns["id"] == stock2_label].copy()
        series1["price_index"] = (1 + series1["stock_ret"]).cumprod() * 1
        series2["price_index"] = (1 + series2["stock_ret"]).cumprod() * 1
    
        len(series1["stock_ret"].dropna())
        # Find the first index where date >= 20150000
        first_idx = series1[series1["date"] >= (year+i) * 10000].index[0]
        
        # Get position of that index
        pos = series1.index.get_loc(first_idx)
        
        # Get 6 rows before that position, plus alldone rows from that position onward
        series1 = series1.iloc[max(0, pos-6):]
        
        series1 = series1[series1["date"] < (year+i+1)*10000]



        
        first_idx = series2[series2["date"] >= (year+i)*10000].index[0]
        
        # Get position of that index
        pos = series2.index.get_loc(first_idx)
        
        # Get 6 rows before that position, plus all rows from that position onward
        series2 = series2.iloc[max(0, pos-6):]
        series2 = series2[series2["date"] < (year+i+1)*10000]
        try:
            temp, temp2 = tp.pairs_trade_monthly_with_risk(series1.set_index('date')["price_index"], series2.set_index('date')["price_index"],
                                                stock1_label, stock2_label)
            df_combined = pd.concat([df_combined, temp2], ignore_index=True)
        except:
            print("skip pair")
    print(year+i, "done")

2015 done
2016 done
2017 done
2018 done
2019 done
2020 done
2021 done
2022 done
2023 done
2024 done
2025 done

In [15]:
df_combined = df_combined[df_combined["holding_months"] > 0]

print(df_combined["pnl_dollars"].sum())
df_combined
df_combined

851.249119343938

,entry_date,exit_date,direction,entry_spread,exit_spread,pnl_dollars,holding_months,close_reason
0,20150130,20150331,SHORT,2.333910,0.911094,11.037340,2,z_cross
1,20150130,20150227,SHORT,-1.370083,-0.518895,1.262078,1,z_cross
2,20150930,20151231,LONG,-0.722755,-1.032880,-6.376105,3,stop_loss
3,20150130,20150331,LONG,-0.594720,-0.727829,3.068234,2,z_cross
4,20150430,20151030,LONG,-0.888278,0.639903,15.147256,6,max_holding
5,20151130,20151231,SHORT,0.836750,0.999899,1.153726,1,forced_liquidation_end_of_sample
6,20150227,20150331,SHORT,2.263286,1.396075,2.770283,1,z_cross
7,20150731,20150831,LONG,1.724290,1.875702,-4.128106,1,stop_loss
8,20150930,20151030,LONG,1.614869,2.866893,14.319756,1,z_cross
9,20150130,20150227,LONG,5.149402,4.451687,-0.133191,1,stop_loss
10,20150529,20150630,LONG,7.120529,2.638816,-2.678700,1,stop_loss
11,20150630,20150731,LONG,0.684827,-0.248197,-7.673671,1,stop_loss
12,20151030,20151130,LONG,-2.196654,-2.801814,-4.359541,1,stop_loss
13,20151030,20151130,LONG,-2.735397,-3.209823,-5.915529,1,stop_loss
14,20150130,20150227,LONG,6.512338,5.809506,2.565509,1,z_cross
15,20151030,20151231,SHORT,6.058049,6.579830,0.939684,2,forced_liquidation_end_of_sample
16,20150130,20150227,SHORT,1.331331,0.737780,5.099248,1,z_cross
17,20150731,20150831,LONG,-0.015916,0.134664,-10.284077,1,stop_loss
18,20151130,20151231,LONG,0.074343,0.410103,-1.462637,1,stop_loss
19,20150430,20150529,SHORT,6.225075,4.188564,8.645940,1,z_cross
20,20150731,20150831,LONG,3.758510,3.000148,-5.203701,1,stop_loss
21,20150930,20151030,LONG,1.459388,0.466936,18.652549,1,z_cross
23,20150130,20150227,LONG,0.389474,0.461783,-4.821234,1,stop_loss
24,20150331,20150430,LONG,0.406526,0.241021,-1.479405,1,stop_loss
25,20150529,20150831,LONG,0.081924,0.190073,-8.255647,3,stop_loss
26,20150130,20150630,SHORT,2.505206,-1.894079,6.090940,5,z_cross
27,20151130,20151231,SHORT,-0.480193,-0.874493,-2.017929,1,stop_loss
28,20150130,20150731,SHORT,3.017062,2.073904,17.770226,6,max_holding
29,20150831,20150930,LONG,1.001418,-0.013164,-0.963090,1,stop_loss
30,20150331,20150430,LONG,-0.239746,-0.119480,-1.592859,1,stop_loss
31,20150529,20150731,LONG,0.218923,0.384201,-5.270728,2,stop_loss
32,20150831,20150930,LONG,0.419195,-0.046060,-1.631317,1,stop_loss
33,20150130,20150430,SHORT,1.933575,0.885779,9.041309,3,z_cross
34,20150227,20150331,SHORT,0.813469,-0.254452,7.922459,1,z_cross
35,20150731,20150930,SHORT,1.818821,3.009554,5.824035,2,z_cross
36,20150227,20150831,LONG,-1.147775,0.023418,34.580377,6,max_holding
37,20150930,20151231,SHORT,1.606771,-2.229080,3.214755,3,forced_liquidation_end_of_sample
38,20150130,20150227,LONG,4.308434,5.203841,4.655765,1,z_cross
39,20150430,20150529,LONG,4.813891,4.081491,-7.924209,1,stop_loss
40,20150630,20150731,LONG,3.064299,2.554102,8.231815,1,z_cross
41,20150130,20150731,SHORT,-5.767811,8.788271,51.571735,6,max_holding
42,20150831,20151130,LONG,9.194227,8.318052,-4.896954,3,stop_loss
44,20150731,20150831,LONG,-2.141836,1.581531,-3.035783,1,stop_loss
45,20150930,20151231,LONG,2.883581,6.410243,1.119731,3,forced_liquidation_end_of_sample
46,20150130,20150227,LONG,9.569004,12.780003,5.979829,1,z_cross
47,20150731,20150831,LONG,13.583277,13.146056,-4.708888,1,stop_loss
48,20150930,20151231,LONG,11.001537,8.752780,-8.310476,3,stop_loss
49,20150331,20150430,SHORT,3.241923,2.939593,-1.480176,1,stop_loss
50,20150529,20150630,SHORT,2.752636,2.189933,4.093279,1,z_cross
51,20150731,20150831,SHORT,2.619089,2.659563,-3.528323,1,stop_loss
52,20150930,20151030,SHORT,3.193346,4.186134,-9.544480,1,stop_loss
53,20150331,20150430,LONG,-2.427606,-0.950718,-0.976633,1,stop_loss
54,20150529,20150630,LONG,-0.641364,0.519267,-5.486410,1,stop_loss
55,20150731,20150930,SHORT,2.681022,0.147473,1.695327,2,z_cross
57,20150430,20150529,SHORT,5.130209,5.248641,7.409790,1,z_cross
58,20150731,20150831,LONG,4.669562,4.013430,-6.046925,1,stop_loss
59,20150930,20151030,LONG,3.322319,3.480089,15.179508,1,z_cross
60,20151130,20151231,LONG,2.854514,2.449617,-5.251395,1,stop_loss
61,20150130,20150227,LONG,8.787046,13.716642,3.325583,1,z_cross
62,20150731,20150930,LONG,14.748752,14.977754,-15.496742,2,stop_loss
63,20151030,20151130,LONG,15.989228,17.158482,-1.511561,1,stop_loss
64,20150731,20150831,SHORT,0.941327,0.667230,6.211944,1,z_cross
66,20150331,20150430,SHORT,0.506270,-0.871645,-1.361648,1,stop_loss
67,20150630,20151231,SHORT,-1.298102,-6.189485,75.379904,6,max_holding
68,20150130,20150529,SHORT,0.523970,0.000402,2.792765,4,z_cross
69,20150630,20150831,SHORT,0.233648,0.367727,-0.168708,2,stop_loss
70,20151130,20151231,LONG,-0.564224,-0.051761,-1.450212,1,stop_loss
71,20150227,20150331,LONG,-5.975670,-1.316059,-0.974328,1,stop_loss
72,20150227,20150331,SHORT,0.761293,-0.340186,-5.990815,1,stop_loss
73,20150430,20150630,SHORT,-0.666924,-1.873779,-1.831196,2,stop_loss
74,20150731,20150831,SHORT,-2.207079,-1.581955,-11.732341,1,stop_loss
75,20150130,20150430,LONG,5.131974,4.537309,-2.277833,3,stop_loss
76,20150529,20150630,LONG,4.073147,3.621991,-2.015206,1,stop_loss
77,20150831,20150930,LONG,3.277730,3.255346,5.872502,1,z_cross
78,20150430,20151030,SHORT,6.967592,5.325431,21.504183,6,max_holding
79,20151130,20151231,LONG,4.358816,3.660253,-6.928857,1,stop_loss
80,20150430,20150529,SHORT,1.740428,3.580210,-1.326123,1,stop_loss
81,20150227,20150331,SHORT,0.023915,0.047542,-1.945779,1,stop_loss
82,20150731,20150831,SHORT,0.507281,0.628023,-0.381002,1,stop_loss
83,20150930,20151030,SHORT,0.977443,1.237760,-1.142484,1,stop_loss
84,20151130,20151231,SHORT,1.545996,2.070478,1.715787,1,forced_liquidation_end_of_sample
85,20150130,20150227,LONG,6.488740,6.015601,2.242682,1,z_cross
86,20151030,20151231,SHORT,6.342140,6.791729,0.146077,2,forced_liquidation_end_of_sample
87,20150227,20150331,SHORT,1.402210,1.284909,-3.281414,1,stop_loss
88,20150930,20151130,LONG,0.776392,1.165539,-0.448195,2,stop_loss
89,20150227,20150430,SHORT,0.817530,-1.285627,2.304773,2,z_cross
90,20150630,20150731,LONG,-1.483766,-0.395010,-12.208876,1,stop_loss
91,20150930,20151231,LONG,2.012510,3.071400,24.413548,3,forced_liquidation_end_of_sample
92,20150331,20150430,SHORT,1.403212,0.628875,-1.198041,1,stop_loss
93,20150630,20150731,SHORT,0.620803,-0.597396,-1.351109,1,stop_loss
94,20151130,20151231,LONG,0.353245,1.222330,0.348770,1,forced_liquidation_end_of_sample
95,20150130,20150529,LONG,2.171213,2.026470,7.522308,4,z_cross
96,20150731,20150831,LONG,1.537456,0.920722,-6.207334,1,stop_loss
97,20150130,20150430,SHORT,-6.700968,1.723939,60.049085,3,z_cross
98,20150831,20150930,LONG,2.096598,2.855974,-5.914571,1,stop_loss
99,20150930,20151030,SHORT,0.470369,0.733873,-3.833296,1,stop_loss
100,20151130,20151231,SHORT,1.249065,2.035173,3.540814,1,forced_liquidation_end_of_sample
101,20150331,20150630,LONG,1.862842,3.413890,4.875393,3,z_cross
102,20150731,20150831,LONG,2.906367,4.205498,-7.245775,1,stop_loss
103,20150930,20151231,LONG,5.102350,7.371346,0.668935,3,forced_liquidation_end_of_sample
104,20150130,20150331,SHORT,-0.899179,0.069305,-1.754806,2,stop_loss
105,20150731,20150831,SHORT,1.088704,2.426998,-28.881166,1,stop_loss
106,20150930,20151030,SHORT,2.739629,3.442779,-7.450864,1,stop_loss
107,20150227,20150331,SHORT,13.312443,13.759388,-3.245238,1,stop_loss
108,20150731,20150930,SHORT,11.634605,16.539065,-4.672800,2,stop_loss
109,20151030,20151130,SHORT,20.354551,22.969573,-0.762227,1,stop_loss
110,20150227,20150430,SHORT,3.052649,3.754832,-6.374447,2,stop_loss
111,20150529,20150630,SHORT,2.675784,3.386118,11.545607,1,z_cross
112,20150227,20150430,LONG,-18.735596,-7.755722,8.818387,2,z_cross
113,20150731,20150831,LONG,-9.977526,-7.849421,-8.963015,1,stop_loss
114,20150930,20151130,LONG,-1.219383,21.960636,-8.280968,2,stop_loss
116,20150331,20150430,SHORT,-2.731814,-1.487496,-3.464660,1,stop_loss
117,20150529,20150630,SHORT,-0.893537,-0.138009,2.121046,1,z_cross
118,20150831,20150930,LONG,-0.313288,-0.761368,-6.452540,1,stop_loss
120,20160129,20160331,SHORT,5.538893,8.393394,-11.033282,2,stop_loss
121,20160331,20160429,SHORT,1.061251,0.153320,2.822252,1,z_cross
122,20160729,20160831,SHORT,0.209418,-0.051757,-0.560895,1,stop_loss
123,20160129,20160229,LONG,2.348054,3.368924,5.080864,1,z_cross
124,20160429,20160531,SHORT,3.486018,3.054370,-1.133520,1,stop_loss
125,20160630,20160831,SHORT,2.650345,1.240881,3.941605,2,z_cross
126,20160129,20160229,LONG,8.385283,5.656590,6.474941,1,z_cross
127,20160930,20161031,LONG,4.402279,4.089886,-2.100827,1,stop_loss
128,20161130,20161230,LONG,3.666548,3.539079,-1.315180,1,stop_loss
129,20160229,20160831,SHORT,0.481186,0.606521,10.013082,6,max_holding
130,20160331,20160531,LONG,-3.048433,0.901756,9.403527,2,z_cross
131,20160331,20160531,SHORT,3.149406,2.969779,7.196224,2,z_cross
132,20160331,20160429,SHORT,7.677708,7.649809,-14.344608,1,stop_loss
133,20160630,20160729,SHORT,3.410311,3.612798,-13.046312,1,stop_loss
134,20160831,20160930,SHORT,4.421134,1.784165,-0.621852,1,stop_loss
135,20160331,20160729,LONG,-1.438437,-0.113313,-2.082569,4,stop_loss
136,20160831,20160930,LONG,0.011455,1.559598,17.838484,1,z_cross
137,20160129,20160229,LONG,2.561228,9.251055,8.445906,1,z_cross
138,20160331,20160429,SHORT,10.938858,7.503737,-6.023625,1,stop_loss
139,20160229,20160331,SHORT,6.005309,7.289916,-5.017582,1,stop_loss
140,20160729,20160831,SHORT,5.055889,3.705969,4.907870,1,z_cross
141,20160229,20160729,SHORT,5.055264,10.360358,13.318243,5,z_cross
142,20161031,20161130,LONG,9.935514,10.661465,-4.437195,1,stop_loss
143,20160129,20160331,SHORT,2.594264,2.064981,-4.652019,2,stop_loss
144,20160531,20161031,LONG,1.591130,1.657177,6.102975,5,z_cross
146,20160129,20160331,SHORT,5.457308,6.541907,-12.877030,2,stop_loss
147,20160129,20160229,SHORT,1.082539,1.593725,3.692864,1,z_cross
148,20160331,20160429,SHORT,1.882359,0.948942,-0.748381,1,stop_loss
149,20160331,20160429,SHORT,6.581709,-0.181105,4.870101,1,z_cross
150,20160129,20160229,SHORT,2.789167,1.951960,-2.712773,1,stop_loss
151,20160429,20160531,LONG,0.571290,1.203103,-8.162573,1,stop_loss
152,20161130,20161230,LONG,1.637547,2.113657,3.845205,1,forced_liquidation_end_of_sample
153,20160129,20160331,LONG,19.312631,20.570213,14.739526,2,z_cross
154,20160930,20161031,SHORT,21.981905,24.461790,-13.279663,1,stop_loss
155,20161130,20161230,SHORT,27.105490,27.670427,2.757605,1,forced_liquidation_end_of_sample
156,20160831,20160930,SHORT,9.293527,9.013718,-11.360061,1,stop_loss
157,20161031,20161230,SHORT,7.782850,5.395453,-1.005222,2,stop_loss
158,20160129,20160229,SHORT,0.152097,0.209229,8.767200,1,z_cross
159,20160729,20161130,LONG,0.015685,0.317363,9.139592,4,z_cross
160,20160229,20160331,LONG,-2.966785,-1.450598,-9.040326,1,stop_loss
161,20160630,20160729,LONG,-0.386582,0.658004,-0.750109,1,stop_loss
162,20160229,20160429,LONG,-0.035090,0.412414,-0.447166,2,stop_loss
163,20160129,20160729,LONG,0.511467,-0.465470,20.788078,6,max_holding
164,20160831,20161230,SHORT,-0.761773,-1.430443,1.123730,4,forced_liquidation_end_of_sample
165,20160229,20160429,LONG,3.941538,4.149206,-1.505175,2,stop_loss
166,20160531,20160729,SHORT,6.388896,3.360463,4.676148,2,z_cross
167,20160831,20160930,LONG,2.948893,3.612283,-5.443408,1,stop_loss
168,20161031,20161230,LONG,4.744168,5.689109,16.191987,2,forced_liquidation_end_of_sample
169,20160129,20160729,LONG,3.329508,3.829605,18.558919,6,max_holding
170,20160930,20161230,SHORT,3.883748,3.654613,40.996860,3,forced_liquidation_end_of_sample
171,20160129,20160229,SHORT,-3.072732,-0.781606,-17.564162,1,stop_loss
172,20160331,20160531,SHORT,1.778448,2.192886,17.769422,2,z_cross
173,20161031,20161130,LONG,1.779541,2.377368,-3.593191,1,stop_loss
174,20160129,20160229,SHORT,0.581158,0.330066,-6.930204,1,stop_loss
176,20160129,20160229,LONG,1.610705,1.782934,4.139223,1,z_cross
177,20160429,20160531,SHORT,1.919269,2.006025,-2.414636,1,stop_loss
178,20160630,20160729,SHORT,2.263222,2.641403,-4.990012,1,stop_loss
179,20160831,20161230,SHORT,2.828145,1.978252,4.659072,4,forced_liquidation_end_of_sample
180,20160429,20160531,LONG,-2.124291,-1.858902,-12.818388,1,stop_loss
181,20160630,20160831,LONG,-0.743303,2.519791,17.141683,2,z_cross
182,20161031,20161130,SHORT,5.311549,5.416906,-5.745114,1,stop_loss
184,20160831,20161031,LONG,-0.360435,0.084073,-1.660490,2,stop_loss
185,20161130,20161230,LONG,-0.166372,0.314192,-0.674100,1,stop_loss
186,20160129,20160729,SHORT,-1.998958,0.681377,59.774503,6,max_holding
187,20161031,20161130,LONG,1.959520,1.939565,-1.606133,1,stop_loss
189,20160331,20160630,SHORT,0.944779,1.846787,2.048128,3,z_cross
190,20160831,20160930,SHORT,2.765178,2.354049,-3.388886,1,stop_loss
191,20160129,20160229,SHORT,2.810878,3.763606,-1.973486,1,stop_loss
192,20160331,20160531,SHORT,4.703337,5.488819,-1.665769,2,stop_loss
193,20160630,20160729,SHORT,5.444558,5.489664,-1.694352,1,stop_loss
194,20160331,20160531,SHORT,5.841443,4.894695,-0.653951,2,stop_loss
195,20160729,20160930,SHORT,4.236382,2.458817,-0.324568,2,stop_loss
197,20160129,20160729,LONG,0.316194,2.452243,23.694520,6,max_holding
198,20160831,20161230,SHORT,2.754770,2.901807,6.547074,4,forced_liquidation_end_of_sample
199,20160229,20160729,SHORT,6.938400,7.789741,21.075947,5,z_cross
200,20161031,20161130,LONG,7.867849,8.594391,-3.445756,1,stop_loss
201,20160129,20160331,LONG,-1.133097,-0.168820,4.877413,2,z_cross
202,20160930,20161031,SHORT,-0.103430,-0.136143,-1.176737,1,stop_loss
203,20161130,20161230,SHORT,-0.197815,-0.199297,-2.633612,1,stop_loss
204,20160129,20160331,SHORT,1.710312,1.718132,-4.556732,2,stop_loss
205,20160429,20160531,SHORT,1.359650,1.204218,-0.351019,1,stop_loss
206,20160630,20161031,SHORT,1.255300,0.897256,-0.763028,4,stop_loss
207,20161130,20161230,SHORT,0.806553,0.911861,-4.909943,1,stop_loss
208,20160129,20160331,SHORT,10.004121,3.802615,-25.678080,2,stop_loss
209,20160429,20160531,SHORT,-1.518672,-2.602093,-7.368500,1,stop_loss
210,20160531,20160630,SHORT,8.363643,8.455350,-3.705884,1,stop_loss
211,20161031,20161130,SHORT,7.058230,8.228449,-4.605093,1,stop_loss
213,20160229,20160331,LONG,-0.830184,-1.517037,-24.255598,1,stop_loss
214,20161031,20161130,SHORT,1.377335,1.329143,28.789461,1,z_cross
215,20160129,20160229,SHORT,1.136951,1.807613,-6.932640,1,stop_loss
216,20160331,20160429,SHORT,2.382983,2.585640,-4.542633,1,stop_loss
217,20161031,20161130,LONG,0.635175,1.609558,9.660369,1,z_cross
218,20160331,20160429,SHORT,2.750744,1.916340,-0.485040,1,stop_loss
219,20160129,20160531,LONG,3.502088,5.191880,1.908075,4,z_cross
220,20160831,20161130,SHORT,5.623340,3.977679,-1.299907,3,stop_loss
222,20170131,20170331,SHORT,0.577633,0.338887,-0.143888,2,stop_loss
223,20170929,20171031,SHORT,0.238652,0.147829,-0.250756,1,stop_loss
225,20170228,20170531,SHORT,0.612449,0.479955,-0.704247,3,stop_loss
226,20170731,20170831,SHORT,0.526738,0.434782,-1.585674,1,stop_loss
227,20170929,20171031,SHORT,0.512676,0.011050,7.370289,1,z_cross
228,20170331,20170428,LONG,0.791924,0.207763,3.583327,1,z_cross
229,20170831,20170929,LONG,-0.071130,-1.162145,-16.853726,1,stop_loss
230,20171031,20171130,LONG,-3.774936,-3.548735,-9.862988,1,stop_loss
232,20170228,20170331,LONG,0.818111,3.347189,2.248729,1,z_cross
233,20170531,20170630,LONG,4.013122,4.883470,-1.975016,1,stop_loss
234,20170831,20171229,LONG,6.146747,5.380469,17.363925,4,forced_liquidation_end_of_sample
235,20170929,20171031,LONG,1.344873,1.321114,-8.369397,1,stop_loss
236,20171130,20171229,LONG,1.817289,3.207912,-2.711370,1,stop_loss
237,20170131,20170428,LONG,0.057823,4.101993,-6.926506,3,stop_loss
238,20171130,20171229,SHORT,5.240244,4.227164,1.133085,1,forced_liquidation_end_of_sample
239,20170731,20170831,SHORT,6.926893,6.468988,-0.504288,1,stop_loss
240,20170929,20171031,SHORT,6.839521,7.911522,-9.610876,1,stop_loss
241,20171130,20171229,SHORT,8.850928,7.977748,-3.421093,1,stop_loss
242,20170428,20170531,LONG,4.647769,4.097642,-10.375706,1,stop_loss
243,20170630,20170731,LONG,3.065103,0.645420,-6.705184,1,stop_loss
244,20170831,20171031,LONG,-1.586093,-0.101564,-0.917922,2,stop_loss
245,20170131,20170228,SHORT,2.827365,4.399809,-2.932864,1,stop_loss
246,20170428,20170531,SHORT,5.699743,5.742378,-6.745386,1,stop_loss
247,20170731,20170929,LONG,1.271908,2.647573,3.036814,2,z_cross
248,20171130,20171229,SHORT,2.991067,2.182305,7.165718,1,z_cross
249,20170131,20170228,SHORT,3.895013,3.386894,-5.933677,1,stop_loss
250,20170428,20170531,SHORT,1.720964,1.294787,-3.654563,1,stop_loss
251,20170630,20171031,SHORT,0.977557,-0.616207,-5.050946,4,stop_loss
252,20171130,20171229,SHORT,-0.567386,-1.047383,-2.535065,1,stop_loss
253,20170531,20170630,LONG,4.516593,3.588214,3.317726,1,z_cross
254,20170131,20170331,SHORT,1.470364,3.346119,2.723559,2,z_cross
255,20170630,20170831,SHORT,3.390243,2.304032,5.287111,2,z_cross
257,20170531,20170731,LONG,2.974996,4.921012,5.600812,2,z_cross
258,20170630,20170831,LONG,0.209919,2.852298,-3.247797,2,stop_loss
259,20170228,20170331,SHORT,5.417992,2.252649,-0.986176,1,z_cross
260,20170831,20171229,LONG,3.080808,3.904761,15.539537,4,forced_liquidation_end_of_sample
261,20170228,20170428,SHORT,16.367735,17.567427,-5.044771,2,stop_loss
262,20170531,20170731,SHORT,19.709471,13.137223,-3.216931,2,stop_loss
263,20170831,20171229,LONG,7.017492,7.213691,24.123333,4,forced_liquidation_end_of_sample
264,20170831,20170929,LONG,3.788252,4.376968,4.706942,1,z_cross
265,20170131,20170228,SHORT,0.513604,4.289924,-4.520710,1,stop_loss
266,20170331,20170531,SHORT,4.586426,6.363318,-1.093473,2,stop_loss
267,20171031,20171229,LONG,3.297224,5.750814,11.650767,2,forced_liquidation_end_of_sample
268,20170228,20170331,SHORT,-0.375391,0.102764,-6.331796,1,stop_loss
269,20170428,20170731,SHORT,1.469476,3.626896,-2.714453,3,stop_loss
270,20171031,20171130,SHORT,4.842852,5.490781,-1.071351,1,stop_loss
272,20170331,20170428,SHORT,25.339613,26.786563,15.030608,1,z_cross
273,20170531,20170731,SHORT,30.533187,7.888302,-0.766955,2,stop_loss
274,20170831,20171130,SHORT,4.248673,-5.047940,-5.704305,3,stop_loss
276,20170531,20170831,LONG,3.142874,5.419716,0.727194,3,z_cross
277,20170630,20170831,LONG,4.782045,6.203370,-4.828684,2,stop_loss
278,20170228,20170331,LONG,7.217224,7.477803,3.511697,1,z_cross
279,20170531,20170630,SHORT,7.768642,7.594296,-2.891345,1,stop_loss
280,20170731,20171031,SHORT,7.251475,5.618117,-0.690983,3,stop_loss
281,20170228,20170331,SHORT,3.046472,1.939539,-1.032288,1,stop_loss
282,20170531,20170731,SHORT,2.659186,2.652125,-0.876333,2,stop_loss
283,20170929,20171031,LONG,0.458764,-0.424138,-9.579324,1,stop_loss
284,20171130,20171229,LONG,0.006019,1.404365,5.606227,1,forced_liquidation_end_of_sample
285,20170331,20170428,SHORT,-0.043234,-1.032044,4.525253,1,z_cross
286,20170630,20170731,LONG,-0.674136,-0.086938,-3.210551,1,stop_loss
287,20170131,20170428,LONG,76.266559,66.869978,-19.520950,3,stop_loss
288,20171130,20171229,SHORT,65.103576,68.354981,-8.076484,1,stop_loss
289,20170428,20170531,LONG,-1.531341,3.142020,-1.580254,1,z_cross
290,20170831,20171130,LONG,3.512442,4.405175,6.905971,3,z_cross
291,20170131,20170331,LONG,6.169422,10.227884,-0.243595,2,stop_loss
292,20170428,20170531,LONG,10.463490,9.679723,-12.900743,1,stop_loss
293,20170630,20170731,LONG,7.510156,-0.465642,-5.880826,1,stop_loss
294,20170929,20171130,LONG,-6.290374,-6.266031,-7.304488,2,stop_loss
295,20170131,20170228,SHORT,7.035248,14.041736,-3.698793,1,stop_loss
296,20171130,20171229,SHORT,21.516924,21.888771,-5.053468,1,stop_loss
297,20170531,20170630,SHORT,2.124579,1.641493,-1.147229,1,stop_loss
298,20170731,20171031,SHORT,1.538929,0.668236,-6.184292,3,stop_loss
299,20170228,20170428,SHORT,5.807283,7.441754,-3.412063,2,stop_loss
300,20170531,20170731,SHORT,8.647228,9.828736,-1.185930,2,stop_loss
302,20170331,20170428,SHORT,8.876484,7.208103,-5.520689,1,stop_loss
303,20170531,20170630,SHORT,4.110184,1.416488,-3.384155,1,stop_loss
304,20170929,20171031,SHORT,-5.576913,-11.034901,28.838377,1,z_cross
305,20170228,20170331,SHORT,64.887348,51.401106,-19.747422,1,stop_loss
306,20170531,20170630,SHORT,33.982900,23.829764,-0.959175,1,stop_loss

In [23]:
# Convert to datetime
df_combined["exit_date"] = pd.to_datetime(df_combined["exit_date"], format="%Y%m%d")

# Extract year-month period
df_combined["year_month"] = df_combined["exit_date"].dt.to_period("M")

# Count trades per month
count_per_month = df_combined.groupby("year_month").size().reset_index(name="count")

# Create full monthly range
full_range = pd.period_range(start=pd.to_datetime(20150130, format="%Y%m%d"), end=df_combined["exit_date"].max(), freq="M")
full_df = pd.DataFrame({"year_month": full_range})

# Merge and fill missing with 0
count_per_month_full = full_df.merge(count_per_month, on="year_month", how="left").fillna(0)
count_per_month_full["count"] = count_per_month_full["count"].astype(int)
count_per_month_full.to_csv("pairs-trade-counts-per-month.csv")

In [5]:
new_df = (
    df_combined.groupby("exit_date")["pnl_dollars"]
      .mean()  # average PnL across rows with same exit_date
      .reset_index(name="avg_pnl_dollars")
)
# new_df["avg_pnl_dollars"] = new_df["avg_pnl_dollars"].cumsum()
new_df

     exit_date  avg_pnl_dollars
0     20150227         2.241808
1     20150331         0.760594
2     20150430         4.615989
3     20150529         2.853412
4     20150630         1.857195
..         ...              ...
110   20250228         3.495048
111   20250331        -1.066412
112   20250430        -1.170146
113   20250530        -6.109636
114   20250630         6.526912

[115 rows x 2 columns]

In [6]:
import numpy as np
new_df["avg_pnl_dollars"] = new_df["avg_pnl_dollars"] / 100 + 1
new_df["log"] = np.log(new_df["avg_pnl_dollars"])
new_df["sum"] = new_df["log"].cumsum()
new_df["bench"] = np.exp(new_df["sum"]) - 1
pd.set_option('display.max_rows', None)
new_df

     exit_date  avg_pnl_dollars       log       sum     bench
0     20150227         1.022418  0.022170  0.022170  0.022418
1     20150331         1.007606  0.007577  0.029748  0.030195
2     20150430         1.046160  0.045126  0.074874  0.077748
3     20150529         1.028534  0.028135  0.103008  0.108501
4     20150630         1.018572  0.018402  0.121410  0.129088
5     20150731         1.072956  0.070418  0.191828  0.211462
6     20150831         0.960013 -0.040809  0.151019  0.163019
7     20150930         0.975845 -0.024451  0.126568  0.134926
8     20151030         1.069813  0.067484  0.194052  0.214160
9     20151130         0.962607 -0.038110  0.155942  0.168759
10    20151231         1.044913  0.043934  0.199876  0.221252
11    20160229         1.000443  0.000443  0.200320  0.221793
12    20160331         0.922506 -0.080661  0.119658  0.127112
13    20160429         0.977329 -0.022932  0.096726  0.101559
14    20160531         1.001424  0.001423  0.098149  0.103127
15    20160630         0.991711 -0.008323  0.089826  0.093984
16    20160729         1.116103  0.109843  0.199669  0.220998
17    20160831         1.070887  0.068487  0.268156  0.307550
18    20160930         0.994500 -0.005516  0.262640  0.300358
19    20161031         0.978537 -0.021697  0.240943  0.272449
20    20161130         1.022857  0.022600  0.263543  0.301533
21    20161230         1.054653  0.053212  0.316755  0.372666
22    20170228         0.956807 -0.044153  0.272601  0.313376
23    20170331         0.994112 -0.005905  0.266696  0.305643
24    20170428         0.990787 -0.009256  0.257440  0.293615
25    20170531         0.970952 -0.029478  0.227962  0.256038
26    20170630         0.996982 -0.003023  0.224939  0.252247
27    20170731         0.996909 -0.003095  0.221844  0.248377
28    20170831         0.997950 -0.002052  0.219792  0.245817
29    20170929         0.934980 -0.067230  0.152562  0.164815
30    20171031         1.001538  0.001536  0.154098  0.166606
31    20171130         0.978173 -0.022069  0.132030  0.141142
32    20171229         1.074458  0.071816  0.203846  0.226109
33    20180228         0.959998 -0.040824  0.163022  0.177063
34    20180329         0.989323 -0.010734  0.152288  0.164495
35    20180430         0.949046 -0.052298  0.099989  0.105159
36    20180531         0.998245 -0.001757  0.098232  0.103219
37    20180629         1.059888  0.058163  0.156396  0.169289
38    20180731         1.015425  0.015307  0.171703  0.187325
39    20180831         1.013244  0.013157  0.184860  0.203050
40    20180928         0.698274 -0.359143 -0.174284 -0.159941
41    20181031         1.025065  0.024756 -0.149527 -0.138885
42    20181130         1.033315  0.032772 -0.116755 -0.110197
43    20181231         1.007947  0.007915 -0.108840 -0.103126
44    20190228         0.825526 -0.191735 -0.300575 -0.259608
45    20190329         0.953923 -0.047173 -0.347748 -0.293723
46    20190430         0.997834 -0.002168 -0.349916 -0.295253
47    20190531         0.983082 -0.017063 -0.366979 -0.307176
48    20190628         0.979059 -0.021163 -0.388142 -0.321684
49    20190731         1.004361  0.004351 -0.383791 -0.318726
50    20190830         0.977954 -0.022293 -0.406084 -0.333746
51    20190930         0.985850 -0.014251 -0.420335 -0.343173
52    20191031         1.009322  0.009279 -0.411056 -0.337050
53    20191129         1.016014  0.015887 -0.395169 -0.326434
54    20191231         1.009999  0.009949 -0.385220 -0.319699
55    20200228         1.059178  0.057493 -0.327727 -0.279440
56    20200331         0.877083 -0.131154 -0.458881 -0.368010
57    20200430         1.054379  0.052952 -0.405929 -0.333643
58    20200529         0.995971 -0.004037 -0.409966 -0.336327
59    20200630         1.006483  0.006462 -0.403504 -0.332025
60    20200731         1.009956  0.009907 -0.393597 -0.325374
61    20200831         1.011175  0.011113 -0.382484 -0.317835
62    20200930         1.111503  0.105713 -0.276771 -0.241772
63    20201030         0.968857 -0.031638 -0.308409 -0.265386
64    20201130         1.057574  0.055978 -0.252432 -0.223091
65    20201231         1.122398  0.115468 -0.136964 -0.127998
66    20210226         0.971506 -0.028907 -0.165871 -0.152845
67    20210331         1.041049  0.040229 -0.125642 -0.118070
68    20210430         0.956397 -0.044582 -0.170224 -0.156524
69    20210528         1.019370  0.019184 -0.151039 -0.140186
70    20210630         0.967272 -0.033276 -0.184315 -0.168326
71    20210730         0.887163 -0.119727 -0.304042 -0.262170
72    20210831         1.047295  0.046210 -0.257832 -0.227275
73    20210930         1.058191  0.056560 -0.201271 -0.182309
74    20211029         0.921104 -0.082183 -0.283454 -0.246822
75    20211130         1.051761  0.050466 -0.232988 -0.207837
76    20211231         0.957895 -0.043017 -0.276005 -0.241191
77    20220228         0.929518 -0.073089 -0.349094 -0.294673
78    20220331         0.956727 -0.044237 -0.393332 -0.325195
79    20220429         0.955074 -0.045966 -0.439298 -0.355511
80    20220531         1.050917  0.049663 -0.389635 -0.322696
81    20220630         1.014977  0.014866 -0.374768 -0.312551
82    20220729         1.197751  0.180445 -0.194323 -0.176608
83    20220831         1.040423  0.039627 -0.154695 -0.143324
84    20220930         0.949401 -0.051925 -0.206620 -0.186671
85    20221031         1.033038  0.032504 -0.174116 -0.159800
86    20221130         1.186742  0.171212 -0.002904 -0.002900
87    20221230         1.127375  0.119892  0.116988  0.124106
88    20230228         0.977515 -0.022741  0.094247  0.098831
89    20230331         0.983120 -0.017024  0.077222  0.080282
90    20230428         0.999828 -0.000172  0.077051  0.080097
91    20230531         1.028339  0.027945  0.104996  0.110706
92    20230630         0.994455 -0.005561  0.099435  0.104547
93    20230731         1.016014  0.015887  0.115323  0.122235
94    20230831         0.997679 -0.002323  0.112999  0.119631
95    20230929         0.972787 -0.027590  0.085409  0.089163
96    20231031         0.966722 -0.033844  0.051565  0.052918
97    20231130         1.060739  0.058966  0.110531  0.116871
98    20231229         1.052824  0.051476  0.162007  0.175868
99    20240229         1.021053  0.020834  0.182841  0.200623
100   20240328         0.998667 -0.001334  0.181507  0.199023
101   20240430         1.016817  0.016677  0.198184  0.219186
102   20240531         0.954463 -0.046606  0.151578  0.163669
103   20240628         0.960337 -0.040471  0.111107  0.117515
104   20240731         1.081202  0.078073  0.189181  0.208259
105   20240830         1.044778  0.043804  0.232985  0.262363
106   20240930         0.958153 -0.042748  0.190237  0.209536
107   20241031         1.044012  0.043071  0.233308  0.262771
108   20241129         1.009356  0.009313  0.242621  0.274585
109   20241231         1.051159  0.049893  0.292514  0.339792
110   20250228         1.034950  0.034354  0.326868  0.386618
111   20250331         0.989336 -0.010721  0.316146  0.371831
112   20250430         0.988299 -0.011770  0.304376  0.355779
113   20250530         0.938904 -0.063042  0.241334  0.272946
114   20250630         1.065269  0.063227  0.304561  0.356030

In [11]:
new_df.to_csv("pair-trade-per-month.csv")

In [9]:
df = pd.read_csv("data/mkt_ind.csv")
df = df[df["year"] >= 2015]
df["ret"] = df["ret"] + 1
df["log"] = np.log(df["ret"])
df["cumulative log"] = df["log"].cumsum()
df["bench"] = np.exp(df["cumulative log"]) - 1
df

         rf  year  month       ret       log  cumulative log     bench
120  0.0000  2015      1  0.968959 -0.031533       -0.031533 -0.031041
121  0.0000  2015      2  1.054893  0.053439        0.021906  0.022148
122  0.0000  2015      3  0.982604 -0.017549        0.004357  0.004366
123  0.0000  2015      4  1.008521  0.008485        0.012842  0.012924
124  0.0000  2015      5  1.010491  0.010437        0.023278  0.023551
125  0.0000  2015      6  0.978988 -0.021236        0.002043  0.002045
126  0.0000  2015      7  1.019742  0.019550        0.021592  0.021827
127  0.0000  2015      8  0.937419 -0.064625       -0.043032 -0.042120
128  0.0000  2015      9  0.973557 -0.026799       -0.069831 -0.067449
129  0.0000  2015     10  1.082983  0.079719        0.009888  0.009937
130  0.0000  2015     11  1.000505  0.000505        0.010393  0.010447
131  0.0001  2015     12  0.982470 -0.017686       -0.007293 -0.007266
132  0.0001  2016      1  0.949265 -0.052068       -0.059360 -0.057633
133  0.0002  2016      2  0.995872 -0.004137       -0.063497 -0.061523
134  0.0002  2016      3  1.065991  0.063905        0.000408  0.000408
135  0.0001  2016      4  1.002699  0.002696        0.003104  0.003108
136  0.0001  2016      5  1.015329  0.015213        0.018317  0.018486
137  0.0002  2016      6  1.000906  0.000906        0.019222  0.019408
138  0.0002  2016      7  1.035610  0.034990        0.054213  0.055709
139  0.0002  2016      8  0.998781 -0.001220        0.052993  0.054422
140  0.0002  2016      9  0.998766 -0.001235        0.051758  0.053121
141  0.0002  2016     10  0.980574 -0.019617        0.032141  0.032663
142  0.0001  2016     11  1.034174  0.033603        0.065744  0.067954
143  0.0003  2016     12  1.018201  0.018037        0.083782  0.087391
144  0.0004  2017      1  1.017884  0.017726        0.101508  0.106839
145  0.0004  2017      2  1.037198  0.036523        0.138031  0.148011
146  0.0003  2017      3  0.999611 -0.000389        0.137642  0.147564
147  0.0005  2017      4  1.009091  0.009050        0.146692  0.157997
148  0.0006  2017      5  1.011576  0.011510        0.158201  0.171402
149  0.0006  2017      6  1.004814  0.004802        0.163004  0.177041
150  0.0007  2017      7  1.019349  0.019164        0.182168  0.199815
151  0.0009  2017      8  1.000546  0.000546        0.182714  0.200471
152  0.0009  2017      9  1.019303  0.019119        0.201833  0.223644
153  0.0009  2017     10  1.022188  0.021946        0.223779  0.250794
154  0.0008  2017     11  1.028083  0.027696        0.251474  0.285920
155  0.0009  2017     12  1.009832  0.009784        0.261258  0.298562
156  0.0011  2018      1  1.056179  0.054657        0.315915  0.371514
157  0.0011  2018      2  0.961053 -0.039726        0.276189  0.318097
158  0.0012  2018      3  0.973115 -0.027253        0.248937  0.282661
159  0.0014  2018      4  1.002719  0.002715        0.251652  0.286148
160  0.0014  2018      5  1.021608  0.021378        0.273030  0.313939
161  0.0014  2018      6  1.004842  0.004831        0.277861  0.320302
162  0.0016  2018      7  1.036022  0.035388        0.313249  0.367861
163  0.0016  2018      8  1.030263  0.029814        0.343063  0.409257
164  0.0015  2018      9  1.004294  0.004285        0.347348  0.415309
165  0.0019  2018     10  0.930597 -0.071929        0.275419  0.317082
166  0.0018  2018     11  1.017859  0.017702        0.293120  0.340604
167  0.0019  2018     12  0.908223 -0.096265        0.196855  0.217568
168  0.0021  2019      1  1.078684  0.075742        0.272597  0.313371
169  0.0018  2019      2  1.029729  0.029296        0.301893  0.352416
170  0.0019  2019      3  1.017924  0.017766        0.319658  0.376657
171  0.0021  2019      4  1.039313  0.038560        0.358219  0.430779
172  0.0021  2019      5  0.934222 -0.068041        0.290178  0.336665
173  0.0018  2019      6  1.068930  0.066658        0.356836  0.428802
174  0.0019  2019      7  1.013128  0.013043        0.369879  0.447559
175  0.0016  2019      8  0.981908 -0.018257        0.351622  0.421371
176  0.0018  2019      9  1.017181  0.017035        0.368657  0.445791
177  0.0015  2019     10  1.020432  0.020226        0.388883  0.475331
178  0.0012  2019     11  1.034047  0.033480        0.422363  0.525562
179  0.0014  2019     12  1.028590  0.028189        0.450552  0.569178
180  0.0013  2020      1  0.998372 -0.001629        0.448922  0.566623
181  0.0012  2020      2  0.915890 -0.087860        0.361063  0.434854
182  0.0012  2020      3  0.874881 -0.133668        0.227395  0.255326
183  0.0000  2020      4  1.126844  0.119421        0.346816  0.414556
184  0.0001  2020      5  1.045282  0.044286        0.391102  0.478610
185  0.0001  2020      6  1.018388  0.018221        0.409324  0.505799
186  0.0001  2020      7  1.055101  0.053637        0.462961  0.588771
187  0.0001  2020      8  1.070065  0.067719        0.530680  0.700087
188  0.0001  2020      9  0.960772 -0.040018        0.490662  0.633396
189  0.0001  2020     10  0.972334 -0.028056        0.462606  0.588207
190  0.0001  2020     11  1.107546  0.102146        0.564752  0.759012
191  0.0001  2020     12  1.037121  0.036449        0.601201  0.824309
192  0.0000  2021      1  0.988863 -0.011199        0.590002  0.803992
193  0.0000  2021      2  1.026091  0.025757        0.615759  0.851061
194  0.0000  2021      3  1.042439  0.041563        0.657322  0.929618
195  0.0000  2021      4  1.052425  0.051097        0.708419  1.030779
196  0.0000  2021      5  1.005487  0.005472        0.713891  1.041920
197  0.0000  2021      6  1.022214  0.021971        0.735862  1.087280
198  0.0000  2021      7  1.022748  0.022493        0.758355  1.134761
199  0.0000  2021      8  1.028990  0.028578        0.786933  1.196649
200  0.0000  2021      9  0.952431 -0.048738        0.738195  1.092156
201  0.0000  2021     10  1.069144  0.066858        0.805053  1.236816
202  0.0000  2021     11  0.991666 -0.008369        0.796685  1.218175
203  0.0001  2021     12  1.043613  0.042689        0.839373  1.314916
204  0.0000  2022      1  0.947415 -0.054018        0.785355  1.193186
205  0.0000  2022      2  0.968639 -0.031863        0.753492  1.124406
206  0.0000  2022      3  1.035773  0.035148        0.788641  1.200403
207  0.0000  2022      4  0.912043 -0.092068        0.696573  1.006863
208  0.0003  2022      5  1.000053  0.000053        0.696626  1.006970
209  0.0006  2022      6  0.916080 -0.087652        0.608974  0.838545
210  0.0008  2022      7  1.091116  0.087201        0.696176  1.006066
211  0.0019  2022      8  0.957560 -0.043367        0.652809  0.920929
212  0.0019  2022      9  0.906604 -0.098049        0.554760  0.741522
213  0.0023  2022     10  1.079863  0.076835        0.631594  0.880606
214  0.0029  2022     11  1.053753  0.052358        0.683952  0.981694
215  0.0033  2022     12  0.941029 -0.060782        0.623170  0.864831
216  0.0035  2023      1  1.061753  0.059921        0.683091  0.979989
217  0.0034  2023      2  0.973888 -0.026459        0.656632  0.928287
218  0.0036  2023      3  1.035052  0.034451        0.691083  0.995876
219  0.0035  2023      4  1.014642  0.014536        0.705619  1.025101
220  0.0036  2023      5  1.002482  0.002479        0.708099  1.030128
221  0.0040  2023      6  1.064728  0.062719        0.770818  1.161533
222  0.0045  2023      7  1.031139  0.030664        0.801482  1.228841
223  0.0045  2023      8  0.982284 -0.017875        0.783606  1.189354
224  0.0043  2023      9  0.951281 -0.049946        0.733660  1.082690
225  0.0047  2023     10  0.978020 -0.022225        0.711435  1.036913
226  0.0044  2023     11  1.089179  0.085424        0.796860  1.218563
227  0.0043  2023     12  1.044229  0.043279        0.840139  1.316689
228  0.0047  2024      1  1.015896  0.015771        0.855910  1.353514
229  0.0042  2024      2  1.051721  0.050428        0.906337  1.475239
230  0.0043  2024      3  1.031019  0.030547        0.936884  1.552018
231  0.0047  2024      4  0.958385 -0.042506        0.894379  1.445816
232  0.0044  2024      5  1.048021  0.046904        0.941283  1.563267
233  0.0041  2024      6  1.034670  0.034082        0.975365  1.652135
234  0.0045  2024      7  1.011321  0.011258        0.986623  1.682160
235  0.0048  2024      8  1.022835  0.022578        1.009200  1.743407
236  0.0040  2024      9  1.020197  0.019996        1.029196  1.798815
237  0.0039  2024     10  0.990103 -0.009946        1.019250  1.771116
238  0.0040  2024     11  1.057301  0.055720        1.074970  1.929904
239  0.0037  2024     12  0.975010 -0.025308        1.049662  1.856686
240  0.0037  2025      1  1.027016  0.026658        1.076320  1.933863
241  0.0033  2025      2  0.985758 -0.014345        1.061975  1.892078
242  0.0034  2025      3  0.942455 -0.059267        1.002709  1.725654
243  0.0035  2025      4  0.992375 -0.007654        0.995054  1.704872
244  0.0038  2025      5  1.061524  0.059705        1.054760  1.871286
245  0.0034  2025      6  1.049607  0.048416        1.103175  2.013721

In [10]:
df.to_csv("pair-trade-per-month.csv")

In [4]:

df_cum_returns = df_combined[df_combined["holding_months"] > 0]
df_cum_returns = df_cum_returns.sort_values(by="exit_date")
df_cum_returns["cumulative_pnl"] = df_cum_returns["pnl_dollars"].cumsum()
df_final = df_cum_returns[["exit_date", "cumulative_pnl"]].drop_duplicates(subset="exit_date", keep="last")

In [23]:
df = pd.read_csv("data/mkt_ind.csv")
df["ret"].cumsum()

0     -0.025290
1     -0.006387
2     -0.025505
3     -0.045613
4     -0.015661
         ...
241    1.824657
242    1.767113
243    1.759488
244    1.821012
245    1.870618
Name: ret, Length: 246, dtype: float64

In [ ]:
len(series1["stock_ret"].dropna())
# Find the first index where date >= 20150000
first_idx = series1[series1["date"] >= 20150000].index[0]

# Get position of that index
pos = series1.index.get_loc(first_idx)

# Get 6 rows before that position, plus all rows from that position onward
series1 = series1.iloc[max(0, pos-6):]

series1 = series1[series1["date"] < 20160000]

first_idx = series2[series2["date"] >= 20150000].index[0]

# Get position of that index
pos = series2.index.get_loc(first_idx)

# Get 6 rows before that position, plus all rows from that position onward
series2 = series2.iloc[max(0, pos-6):]
series2 = series2[series2["date"] < 20160000]

df = pd.DataFrame({
    'p1': series1.set_index('date')["stock_ret"], 
    'p2': series2.set_index('date')["stock_ret"]
}).dropna().copy()

In [ ]:
df

In [61]:
foo = tp.pairs_trade_monthly_with_risk(series1.set_index('date')["stock_ret"], series2.set_index('date')["stock_ret"])
foo

const   -0.006543
p2       1.400523
dtype: float64
const   -0.006403
p2       1.401835
dtype: float64
const   -0.004313
p2       1.363977
dtype: float64
const   -0.006588
p2       1.377345
dtype: float64
const   -0.002709
p2       1.330490
dtype: float64
const   -0.003752
p2       1.332470
dtype: float64
const   -0.003741
p2       1.332244
dtype: float64
const   -0.004297
p2       1.312564
dtype: float64
const   -0.002955
p2       1.295675
dtype: float64
const   -0.001791
p2       1.324493
dtype: float64
const   -0.003005
p2       1.326607
dtype: float64
const   -0.005005
p2       1.334433
dtype: float64

,entry_date,exit_date,direction,entry_spread,exit_spread,pnl_dollars,holding_months,close_reason
0,20150430,20150630,SHORT,0.027934,-0.003623,24250.418601,2,z_cross
1,20151130,20151231,LONG,-0.035688,0.019019,35709.582002,1,forced_liquidation_end_of_sample

df_comb

In [7]:
series1 = df_returns[stock1_label]
series2 = df_returns[stock2_label]
plt.figure(1, figsize=(20,8))
plt.plot(serie)
plt.plot(series1_values)
plt.show()

NameError: name 'series2_values' is not defined

In [40]:
entry=2.0
exit=0.5
lookback=6
capital=10000
max_holding=6      # months
stop_loss_pct=0.10
df = pd.DataFrame({'p1': stock1_returns, 'p2': stock2_returns}).dropna().copy()
n = len(df)
if n < lookback + 1:
    raise ValueError("Not enough data for lookback")

trades = []
position = 0              # -1 short spread, +1 long spread, 0 flat
entry_spread = None
entry_date = None
entry_sigma = None
entry_index = None
holding = 0

# Pre-allocate columns
df['z'] = np.nan
df['action'] = ''
df['position'] = 0
df['pnl_unrealized'] = 0.0

for t in range(lookback, n):
    # Use history up to t-1 (no lookahead)
    hist = df.iloc[:t]
    y = hist['p1']
    x = hist['p2']
    X = sm.add_constant(x)
    print(f"X shape: {X.shape}")
    print(f"X columns: {X.columns}")
    print(f"X head:\n{X.head()}")
    model = sm.OLS(y, X).fit()
    print(f"Model params: {model.params}")
    beta = model.params[1]

X shape: (6, 1)
X columns: Index(['p2'], dtype='object')
X head:
               p2
date
20140107  0.23195
20140114  0.23195
20140120  0.23195
20140122  0.23195
20140123  0.23195
Model params: p2   -0.027454
dtype: float64

IndexError: index 1 is out of bounds for axis 0 with size 1